mysql:
    image: mysql
    container_name: database-teste
    ports:
        - 3306:3306
    environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: 123456

php:
    # image: php:fpm-alpine
    image: ermacmk/php-fpm-pdo
    container_name: php-teste
    volumes:
        - .:/var/www/laravel
    entrypoint:
        - php-fpm

nginx:
    image: nginx:alpine
    container_name: nginx-teste
    volumes_from:
        - php
    volumes:
        - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
    ports:
        - 8080:80
