mysql:
    image: mysql
    container_name: mysql
    ports:
        - 3307:3306
    environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: 123456

php:
    # image: php:fpm-alpine
    image: ermacmk/php-fpm-pdo
    container_name: php-teste
    volumes:
        - .:/var/www/laravel
    entrypoint:
        - php-fpm

nginx:
    image: nginx:alpine
    container_name: nginx-server
    volumes_from:
        - php
    volumes:
        - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
    ports:
        - 90:80

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
        - mysql:db
    ports:
        - 9090:80
